students:
  - login:  <%= ENV['STUDENT_1_LOGIN'] %>
    password:  <%= ENV['STUDENT_1_PASSWORD'] %>
  - login:  <%= ENV['STUDENT_2_LOGIN'] %>
    password:  <%= ENV['STUDENT_2_PASSWORD'] %>
  - login:  <%= ENV['STUDENT_3_LOGIN'] %>
    password:  <%= ENV['STUDENT_3_PASSWORD'] %>
  - login:  <%= ENV['STUDENT_4_LOGIN'] %>
    password:  <%= ENV['STUDENT_4_PASSWORD'] %>
  - login:  <%= ENV['STUDENT_5_LOGIN'] %>
    password:  <%= ENV['STUDENT_5_PASSWORD'] %>

login_url: <%= ENV['LOGIN_URL'] %>

subject_urls:
  - <%= ENV['SUBJECT_URL_1'] %>
  - <%= ENV['SUBJECT_URL_2'] %>
  - <%= ENV['SUBJECT_URL_3'] %>
  - <%= ENV['SUBJECT_URL_4'] %>
  - <%= ENV['SUBJECT_URL_5'] %>
  - <%= ENV['SUBJECT_URL_6'] %>
